name: "book"

on:
  push:
    branches:
      - main


jobs:
  jupyter:
    runs-on: "ubuntu-latest"
    steps:
      - uses: cvxgrp/.github/actions/jupyter@main

  book:
    runs-on: "ubuntu-latest"
    needs: [jupyter]

    permissions:
      contents: write

    steps:
      - uses: cvxgrp/.github/actions/book@main
